# Generated by Django 4.0.2 on 2022-02-04 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_expense'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
