# Generated by Django 4.0.2 on 2022-02-04 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='titles',
            new_name='title',
        ),
    ]
